server:
  port: 8086

spring:
  application:
    name: tourism-service
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/tourism-service
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      encoding: UTF-8
